//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VagvolgyiBalazs_beadando_20201206.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VagvolgyiBalazs_beadando_20201206.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pnd1;Pendulum;Hold Your Colour;2005-07-25
        ///pnd2;Pendulum;In Silico;2008-05-12
        ///pnd3;Pendulum;Immersion;2010-05-24.
        /// </summary>
        internal static string albums {
            get {
                return ResourceManager.GetString("albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hold_your_colour {
            get {
                object obj = ResourceManager.GetObject("hold_your_colour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap immersion {
            get {
                object obj = ResourceManager.GetObject("immersion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap in_silico {
            get {
                object obj = ResourceManager.GetObject("in_silico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prelude;0:52;pnd1;null
        ///Slam;5:44;pnd1;gIOQfdn9L9c
        ///Plasticworld;6:21;pnd1;null
        ///Fasten Your Seatbelt;6:38;pnd1;null
        ///Through the Loop;6:13;pnd1;null
        ///Sounds of Life;5:21;pnd1;null
        ///Girl in the Fire;4:53;pnd1;null
        ///Tarantula;5:31;pnd1;null
        ///Out Here;6:07;pnd1;null
        ///Hold Your Colour;5:28;pnd1;null
        ///The Terminal;5:42;pnd1;null
        ///Streamline;5:23;pnd1;null
        ///Another Planet;7:38;pnd1;null
        ///Still Grey;7:51;pnd1;null
        ///Showdown;5:27;pnd2;X6BKBIOtRXw
        ///Different;5:51;pnd2;null
        ///Propane Nightmares;5:13;pnd2;WPbeEtjo70g
        ///Visions;5:36;pnd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tracks {
            get {
                return ResourceManager.GetString("tracks", resourceCulture);
            }
        }
    }
}
